#!/bin/bash

# Load environment variables
source .env

# Launch the Flutter app in development mode
flutter run --flavor development --target lib/main_development.dart \
	--dart-define WEATHER_API_KEY=$WEATHER_API_KEY \
	--dart-define FIREBASE_ANDROID_API_KEY=$FIREBASE_ANDROID_API_KEY \
	--dart-define FIREBASE_ANDROID_APP_ID=$FIREBASE_ANDROID_APP_ID \
	--dart-define FIREBASE_ANDROID_MESSAGING_SENDER_ID=$FIREBASE_ANDROID_MESSAGING_SENDER_ID \
	--dart-define FIREBASE_ANDROID_PROJECT_ID=$FIREBASE_ANDROID_PROJECT_ID \
	--dart-define FIREBASE_ANDROID_STORAGE_BUCKET=$FIREBASE_ANDROID_STORAGE_BUCKET \
	--dart-define FIREBASE_IOS_API_KEY=$FIREBASE_IOS_API_KEY \
	--dart-define FIREBASE_IOS_APP_ID=$FIREBASE_IOS_APP_ID \
	--dart-define FIREBASE_IOS_MESSAGING_SENDER_ID=$FIREBASE_IOS_MESSAGING_SENDER_ID \
	--dart-define FIREBASE_IOS_PROJECT_ID=$FIREBASE_IOS_PROJECT_ID \
	--dart-define FIREBASE_IOS_STORAGE_BUCKET=$FIREBASE_IOS_STORAGE_BUCKET \
	--dart-define FIREBASE_IOS_CLIENT_ID=$FIREBASE_IOS_CLIENT_ID \
	--dart-define FIREBASE_IOS_BUNDLE_ID=$FIREBASE_IOS_BUNDLE_ID
