name: five_on_four_flutter_tdd
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  go_router: ^7.0.0
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  collection: ^1.17.0
  flutter_riverpod: ^2.3.2
  rxdart: ^0.27.7
  hooks_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  flutter_hooks: ^0.18.6
  logger: ^1.3.0
  dependency_validator: ^3.2.2
  flutter_secure_storage: ^8.0.0
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  flutter_dotenv: ^5.0.2
  dio: ^5.1.2
  geocoding: ^2.1.0
  firebase_messaging: ^14.6.1
  overlay_support: ^2.1.0
  cloud_functions: ^4.3.1
  flutter_svg: ^2.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  riverpod_lint: ^1.1.6
  riverpod_generator: ^2.1.4
  network_image_mock: ^2.1.1
  geolocator: ^9.0.2

flutter_launcher_icons:
  image_path: "assets/icons/launcher_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/icons/
    - assets/images/logo/
