name: Android release

# define triggers
on:
  push:
    branches:
      - chore/deploy-v2
  # TODO we can do pull laster
  # pull_request:
  #   branches:
  #     - main
  # TODO i dont know what this is
  workflow_dispatch:

# define jobs
jobs:
  # building the app
  # define name for the job
  build:
    runs-on: ubuntu-latest

    # lets define steps
    steps:
      # checkout the code
      - uses: actions/checkout@v3

      # create .env file, because we are not pushing it to the repo
      - name: Create .env file
        run: |
          touch .env

      # set up java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"
          # TODO might be good to cache this, but it might fail bc of it
          cache: "gradle"

      # set up flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.3"
          channel: "stable"
          # TODO might be good to cache this, but it might fail bc of it
          cache: true

      # install dependencies
      - name: Install dependencies
        run: flutter pub get

      # run tests
      # - name: Run tests
      #   run: flutter test

      # build apk
      # TODO possibly not needed this - app bundle might be better in future
      # TODO not that this will build --debug version?
      - name: Build APK
        # run: flutter build apk --flavor=production --target=lib/main_production.dart --debug --split-per-abi
        run: flutter build apk --flavor=production --target=lib/main_production.dart --split-per-abi

      # build app bundle
      # TODO use this later
      # - name: Build app bundle
      #   run: flutter build appbundle --flavor=production --target=lib/main_production.dart --debug
